[TP-274] physical stock module based on stockist stores
peter-rusin/magento2-convert-m2ce pull request #6
Opened 2021-12-09 14:54 UTC by peter-rusin

2021-12-10 12:32 UTC, bartekAtconvert requested changes

2021-12-10 12:32 UTC, bartekAtconvert commented on app/code/Convert/PhysicalStock/Block/PhysicalStock.php
> +    public function getConfig() : Config
please remember about proper PHPDocs. Have you got yet our coding guidelines? https://convert.atlassian.net/wiki/spaces/M2/pages/628097060/Coding+guidelines

2021-12-10 12:32 UTC, bartekAtconvert commented on app/code/Convert/PhysicalStock/etc/di.xml
> +    <type name="Convert\PhysicalStock\ViewModel\CurrentProduct">
where is this CurrentProduct view model used?

2021-12-10 12:32 UTC, bartekAtconvert commented on app/code/Convert/PhysicalStock/view/frontend/layout/catalog_product_view.xml
> +<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
- why Convert\PhysicalStock\Block\PhysicalStock is rendered 2 times?
- remember the requirements: " under “Add to Cart” button. Show only if the module enabled in Admin. "

2021-12-10 12:32 UTC, bartekAtconvert commented on app/code/Convert/PhysicalStock/view/frontend/templates/product/view/physical-stock.phtml
> +<?php if ($block->getConfig()->isEnabled() && $block->getProduct()) : ?>
it's better to put this condition in layout

2021-12-10 13:39 UTC, peter-rusin commented on app/code/Convert/PhysicalStock/view/frontend/layout/catalog_product_view.xml
> +<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
add to cart button is added twice - once for simple products and once for configurable, 

![photo](https://user-images.githubusercontent.com/10116791/145582681-7068052e-faf7-4523-8278-c85212f5b7d6.png)

I moved the new block to another `referenceContainer` which seems to be cleaner solution

2021-12-10 13:40 UTC, peter-rusin commented on app/code/Convert/PhysicalStock/etc/di.xml
> +    <type name="Convert\PhysicalStock\ViewModel\CurrentProduct">
leftovers, removed it

2021-12-10 13:44 UTC, peter-rusin commented on app/code/Convert/PhysicalStock/Block/PhysicalStock.php
> +    public function getConfig() : Config
I'm not sure why this is wrong, coding guidelines state:
`9. A typed method signature SHOULD be preferred over PHPDoc annotations whenever possible.`

2021-12-13 09:24 UTC, bartekAtconvert commented on app/code/Convert/PhysicalStock/Block/PhysicalStock.php
> +    public function getConfig() : Config
Good point

2021-12-13 09:26 UTC, bartekAtconvert approved these changes
much better now :-)

2021-12-13 09:31 UTC, merged